[[envelopes]]
name = "groceries"
category = "necessary"
allocation = 500.0
is_individual = false
rollover = false

[[envelopes]]
name = "eating-out"
category = "quality_of_life"
allocation = 200.0
is_individual = false
rollover = false

[[envelopes]]
name = "hobby"
category = "quality_of_life"
allocation = 100.0
is_individual = true
rollover = true

[[envelopes]]
name = "personal-fun-money"
category = "quality_of_life"
allocation = 75.0
is_individual = true
rollover = true
