[[envelopes]]
name = "groceries"
category = "necessary"
allocation = 500.0
is_individual = false
rollover = false

[[envelopes]]
name = "eating-out"
category = "quality_of_life"
allocation = 150.0
is_individual = false
rollover = false

[[envelopes]]
name = "game"
category = "quality_of_life"
allocation = 80.0
is_individual = true
rollover = true

[[envelopes]]
name = "drink"
category = "quality_of_life"
allocation = 60.0
is_individual = true
rollover = false
