# Cargo build configuration for EnvelopeBuddy

# Cross-compilation configuration for Raspberry Pi
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Aliases for common tasks
[alias]
# Cross-compile for Raspberry Pi (using cross)
pi = "build --release --target aarch64-unknown-linux-gnu"
